dbt_core_bigquery:
  outputs:
    dev:
      dataset: "{{ env_var('DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: "{{ env_var('LOCATION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('PROJECT') }}"
      threads: 1
      type: bigquery
  target: dev