services:
  pgdatabase:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DATA}
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - nba_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "./pgadmin:/var/lib/pgadmin:rw"
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - nba_network
    user: root

  scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./NBA_scraper/.scrapy:/app/NBA_scraper/.scrapy"
    command: [ "scrapy", "crawl", "bref_spider" ]
    networks:
      - nba_network
    depends_on:
      pgdatabase:
        condition: service_healthy
        restart: true
    restart: unless-stopped

networks:
  nba_network:
    name: nba_network
